spring:
  application:
    name: sz-forest
  profiles:
    active: @profile.name@
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 8099
version: 1.0
resource:
  domain: http://10.26.201.17:32240 # 网站域名
  file-path: http://10.26.201.17:32240/static # 上传文件前缀域名
  real-path: ../static # 上传文件存储地址
