spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  redis:
    database: 2
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: ''
    port: 6379
  datasource:
    url: jdbc:mysql://10.26.200.29:3306/forest-dev?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: szms
    password: szms@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    resources:
      add-mappings: true
  mail:
    host: smtp.163.com # 网站发送邮件邮箱服务 host
    port: 465
    username: # 邮箱
    password: # 密码
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
wx:
  open:
    componentAppId: #
    componentSecret: #
    componentToken: #
    componentAesKey: #
  mp:
    configs:
      - appId: xxx #微信公众号消息服务器配置的 appId
        secret: xxx #微信公众号消息服务器配置的 secret
        token: xxx #微信公众号消息服务器配置的 token
        aesKey: xxx #微信公众号消息服务器配置的 aesKey
  miniapp:
    configs:
      - appid: #微信小程序消息服务器配置的 appid
        secret: #微信小程序消息服务器配置的 secret
        token: #微信小程序消息服务器配置的 token
        aesKey: #微信小程序消息服务器配置的 EncodingAESKey
        msgDataFormat: JSON
env: dev
logging:
  file:
    path: /logs/forest
  level:
    com:
      rymcu: info
server:
  port: 8099
  servlet:
    context-path: /forest
version: 1.0
resource:
  domain: http://yourdomain.com # 网站域名
  file-path: http://yourdomain.com # 上传文件前缀域名
  pic-path: /yoursrc/xx/nebula/static # 上传文件存储地址
baidu:
  data:
    site: https://yourdomain.com # 百度搜索绑定网站域名
    token: xxxx
  ai:
    appId: xxx # 百度AI-文字识别 应用 appId
    appKey: xxxx # 百度AI-文字识别 应用 appKey
    secretKey: xxxx # 百度AI-文字识别 应用 secretKey
#第三方登录
justauth:
  enabled: true
  type:
    GITLAB:
      client-id: 3e06178e2a8730ae7f89dcbcf00708eb072d605ba1ad7e4d1462c75a1a93ef87
      client-secret: 8f0a663e8addcf6621ddc4937f2f5d2041ff8c614948062ec31e28f1630ffe31
      redirect-uri: http://localhost:8099/forest/api/v1/thirdLogin/gitlab/callback
  cache:
    type: default
    prefix: 'NEBULA::THIRD_LOGIN'
    timeout: 1h
third:
  authorize: http://10.26.201.103:9000/oauth/authorize
  accessToken: http://10.26.201.103:9000/oauth/token
  userInfo: http://10.26.201.103:9000/api/v4/user
  loginCallBackUrl: http://localhost:3000/login?
